[package]
name = "cli"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Command-line 9P client for the r9p communication suite"
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "r9p"
path = "src/main.rs"
doc = false

[dependencies]
clap.workspace = true
fuse.workspace = true
fs.workspace = true
libc.workspace = true
r9p.workspace = true
r9p-auth.workspace = true
r9p-reverse.workspace = true
rustix.workspace = true
session.workspace = true
