[package]
name = "front"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Embeddable in-memory 9P front for the r9p communication suite"
repository.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
r9p.workspace = true

[dev-dependencies]
fs.workspace = true
