[package]
name = "beam-port"
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"
description = "BEAM port adapter for long-running Gleam and Erlang apps using r9p"
repository = "https://github.com/MrVampy/r9p"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"

[[bin]]
name = "r9p-beam-port"
path = "src/main.rs"

[dependencies]
front = { path = "../front" }
r9p.workspace = true
