[package]
name = "beam-port"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "BEAM port adapter for long-running Gleam and Erlang apps using r9p"
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "r9p-beam-port"
path = "src/main.rs"

[dependencies]
front.workspace = true
r9p.workspace = true
